import { test, expect } from '@playwright/test'

test('Gantt extraction: controlled drag, constraints, resize, React and virtual rows', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.goto('/#gantt/button')
  await expect(page).toHaveURL(/#components\/gantt$/)
  await expect(page.getByRole('heading', { name: '组件实验室' })).toBeVisible()
  await expect(page.locator('.catalog-card.selected')).toContainText('GanttChart')
  await page.getByRole('tab', { name: '使用代码' }).click()
  await expect(page.locator('.code-panel pre')).toContainText('applyGanttTaskChange')
  await page.getByRole('tab', { name: 'API 文档' }).click()
  await expect(page.locator('.api-panel')).toContainText('zoomPercent')
  await page.getByRole('tab', { name: '组件源码' }).click()
  await expect(page.locator('.code-panel pre')).toContainText('defineProps')
  await page.getByRole('tab', { name: '交互预览' }).click()
  const task = () => page.locator('.yc-gantt-task-bar[aria-label="任务 01"]')
  await expect(task()).toBeVisible()
  async function drag(dx: number, dy = 0, handle?: string) {
    const element = handle ? task().locator(handle) : task()
    await element.scrollIntoViewIfNeeded()
    const box = (await element.boundingBox())!
    const x = box.x + (handle ? box.width / 2 : 10)
    await page.mouse.move(x, box.y + box.height / 2)
    await page.mouse.down()
    await page.mouse.move(x + dx, box.y + box.height / 2 + dy, { steps: 8 })
    await page.mouse.up()
  }
  await drag(24)
  await expect(page.getByRole('status')).toContainText('已应用 task-1')
  await drag(0, 36)
  await expect(page.getByRole('status')).toContainText('时间冲突')
  await page.getByLabel('允许重叠', { exact: true }).check()
  await drag(0, 36)
  await expect(page.locator('[data-row-key="resource-2"] .yc-gantt-task-bar[aria-label="任务 01"]')).toBeVisible()
  await drag(0, 36)
  await expect(page.getByRole('status')).toContainText('不支持资源')
  await page.getByRole('button', { name: '重置数据' }).click()
  await drag(24, 0, '.yc-gantt-task-bar__resize-handle--end')
  await expect(page.getByRole('status')).toContainText('已应用 task-1')
  await drag(280)
  await expect(page.getByRole('status')).toContainText('不可用区间')
  await page.getByLabel('只读', { exact: true }).check()
  await expect(task()).toHaveAttribute('aria-disabled', 'true')
  await page.getByLabel('只读', { exact: true }).uncheck()
  const original = await task().boundingBox()
  await page.mouse.move(original!.x + 20, original!.y + 10)
  await page.mouse.down()
  await page.mouse.move(original!.x + 60, original!.y + 10)
  await page.keyboard.press('Escape')
  await page.mouse.up()
  await expect(page.locator('.yc-gantt-timeline--dragging')).toHaveCount(0)
  await page.getByRole('button', { name: '重置数据' }).click()
  await page.locator('.lab-tabs .framework-switch').getByRole('button', { name: 'React', exact: true }).click()
  await expect(page.locator('[data-yancraft-react="GanttChart"]')).toBeVisible()
  await drag(24)
  await expect(page.getByRole('status')).toContainText('已应用 task-1')
  await task().click({ button: 'right' })
  await expect(page.getByRole('status')).toContainText('任务右键')
  await page.getByLabel('1000 行').check()
  expect(await page.locator('.yc-gantt-timeline__row').count()).toBeLessThan(25)
  await page.locator('.yc-gantt-timeline').evaluate(el => { el.scrollTop = 18000 })
  await expect(page.locator('[data-row-key="resource-500"]')).toBeVisible()
  await page.getByLabel('1000 行').uncheck()
  await page.screenshot({ path: 'test-results/gantt-desktop.png', fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/gantt-mobile.png', fullPage: true, animations: 'disabled' })
  expect(errors).toEqual([])
})
