import { test, expect } from '@playwright/test'
test('catalog, real Vue / React previews, source, documentation and mobile layout', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '好组件，让想法更快发生。' })).toBeVisible()
  await page.evaluate(() => document.fonts.ready.then(() => undefined))
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
  await page.getByRole('textbox', { name: '搜索组件' }).fill('不存在')
  await expect(page.getByText('没有找到匹配的组件')).toBeVisible()
  await page.getByRole('button', { name: '重置筛选' }).click()
  await expect(page.locator('.catalog-card')).toHaveCount(3)
  await page.getByLabel('按钮文案').fill('立即保存')
  await page.locator('.preview-canvas').getByRole('button', { name: '立即保存' }).click()
  await expect(page.getByRole('status')).toContainText('click 事件已触发')
  await page.locator('.ui-switch').getByRole('button', { name: 'Element' }).click()
  await expect(page.locator('.preview-canvas .el-button')).toBeVisible()
  await page.getByRole('switch', { name: '禁用状态' }).check()
  await expect(page.locator('.preview-canvas button')).toBeDisabled()
  await page.getByRole('switch', { name: '禁用状态' }).uncheck()
  await page.locator('.framework-switch').getByRole('button', { name: 'React' }).click()
  await expect(page.locator('[data-yancraft-react="ActionButton"] button')).toHaveText('立即保存')
  await page.getByLabel('按钮文案').fill('React 保存')
  await page.locator('[data-yancraft-react] button').click()
  await expect(page.getByRole('status')).toContainText('click 事件已触发')
  await page.getByRole('tab', { name: '使用代码' }).click()
  await expect(page.locator('.code-panel pre')).toContainText('@yancraft/react')
  await expect(page.locator('.code-panel pre')).toContainText('React 保存')
  await page.getByRole('tab', { name: 'API 文档' }).click()
  await expect(page.getByRole('table')).toContainText('disabled')
  await page.locator('.catalog-card').filter({ hasText: 'EmptyState' }).click()
  await page.locator('.preview-canvas').getByRole('button', { name: '创建项目' }).click()
  await expect(page.getByRole('status')).toContainText('action 事件已触发')
  await page.locator('.catalog-card').filter({ hasText: 'StatCard' }).click()
  await page.getByLabel('指标值').fill('99,999')
  await expect(page.locator('.preview-canvas')).toContainText('99,999')
  await page.getByRole('tab', { name: '组件源码' }).click()
  await expect(page.locator('.code-panel')).toContainText('defineProps<StatCardProps>')
  await page.screenshot({ path: 'test-results/source.png', fullPage: true })
  await page.locator('.nav-item').filter({ hasText: '构建与发布' }).click()
  await expect(page.getByRole('heading', { name: '发布前，先验证产物' })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '打开导航' }).click()
  await page.locator('.nav-item').filter({ hasText: '组件总览' }).click()
  await page.getByRole('tab', { name: '交互预览' }).click()
  await expect(page.locator('.preview-canvas')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
  expect(errors).toEqual([])
})
