import buttonSource from '../../../packages/vue/src/components/ActionButton.vue?raw'
import statSource from '../../../packages/vue/src/components/StatCard.vue?raw'
import emptySource from '../../../packages/vue/src/components/EmptyState.vue?raw'
import editorSource from '../../../packages/vue/src/components/CodeEditor.vue?raw'
import ganttSource from '../../../packages/vue/src/gantt/GanttChart.vue?raw'
export const catalog = [
  { id: 'editor', name: 'CodeEditor', title: '代码编辑器', category: '通用', desc: '让代码与 Markdown，在同一处被编辑与阅读。', details: '基于 CodeMirror 6，支持 13 种语言的语法高亮与 Markdown 编辑、分屏和预览。', source: editorSource, props: [['modelValue', 'string', "''", '编辑器内容'], ['language', 'EditorLanguage', 'typescript', '语言及语法高亮'], ['mode', 'edit | split | preview', 'edit', 'Markdown 展示模式'], ['theme', 'dark | light', 'dark', '编辑器主题'], ['readonly', 'boolean', 'false', '只读模式'], ['lineNumbers', 'boolean', 'true', '显示行号'], ['minHeight', 'number', '300', '最小高度'], ['tabSize', 'number', '2', 'Tab 缩进宽度'], ['wordWrap', 'boolean', 'false', '自动换行']], event: 'update:modelValue / change', eventDesc: '内容变化时同步 v-model 并触发 change。' },
  { id: 'button', name: 'ActionButton', title: '操作按钮', category: '通用', desc: '让每一次操作，都有清晰的回应。', details: '统一两套 UI 库的按钮接口，支持主次操作、危险操作、加载与禁用状态。', source: buttonSource, props: [['label', 'string', '创建项目', '按钮文案'], ['ui', "ant | element", 'ant', '底层 UI 组件库'], ['variant', 'primary | default | danger', 'primary', '操作类型'], ['size', 'small | default | large', 'default', '按钮尺寸'], ['loading', 'boolean', 'false', '加载状态'], ['disabled', 'boolean', 'false', '禁用状态']], event: 'click(event: MouseEvent)', eventDesc: '点击按钮时触发；加载和禁用时不会触发。' },
  { id: 'stat', name: 'StatCard', title: '统计卡片', category: '数据展示', desc: '将关键数字，变成一眼可见的洞察。', details: '展示核心指标与变化率。底部折线为装饰示意，不表示真实时间序列；业务趋势图请接入图表组件。', source: statSource, props: [['title', 'string', '总访问量', '指标标题'], ['value', 'string | number', '128,640', '指标值'], ['change', 'number', '12.8', '变化百分比，负数表示下降'], ['description', 'string', '较上一个周期', '辅助说明']], event: '无', eventDesc: '纯展示组件，支持通过 CSS 变量定制主题。' },
  { id: 'empty', name: 'EmptyState', title: '空状态', category: '反馈', desc: '即使空无一物，也有下一步的方向。', details: '用于列表、搜索和项目空间的空状态，支持自定义文案与行动按钮。actionLabel 设为空字符串可隐藏按钮。', source: emptySource, props: [['title', 'string', '这里还没有内容', '标题'], ['description', 'string', '从第一个项目开始，让想法发生。', '说明文案'], ['actionLabel', 'string', '创建项目', '操作文案，空字符串隐藏按钮'], ['ui', 'ant | element', 'ant', '按钮使用的 UI 库']], event: 'action()', eventDesc: '点击行动按钮时触发。' }
,
  { id: 'gantt', name: 'GanttChart', title: '资源甘特图', category: '数据展示', desc: '拖拽排程，让资源与时间清晰有序。', details: '支持资源排程、拖动与时长调整，提供约束校验和虚拟滚动。通过右侧参数探索真实交互。', source: ganttSource, props: [['rows', 'GanttRow[]', '必填', '资源与任务数据'], ['start / end', 'string', '必填', '时间轴起止范围'], ['height', 'number', '420', '视口高度'], ['zoomPercent', 'number', '100', '时间轴缩放百分比'], ['readonly', 'boolean', 'false', '全图只读'], ['allowOverlap', 'boolean', 'false', '允许任务重叠'], ['unavailableTimeRanges', 'GanttUnavailableRange[]', '[]', '不可用时段'], ['shifts', 'GanttShift[]', '[]', '班次表头']], event: 'task-change / change-rejected', eventDesc: '父级应用变更，或接收约束拒绝原因。' }
] as const
export type ComponentId = typeof catalog[number]['id']
